config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin_useres, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
 
  
  
  
  root to: 'home#index'
  
  resources :curriculos, except: [:index, :destroy, :new, :create]
  resources :vagas, only: [:index, :show]
  resources :candidatos, except: [:show]
  
  devise_for :usuarios, path: "", controllers: { sessions: "usuarios/sessions", registrations: "usuarios/registrations" }, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout'}

  
  

end

app/models/curriculo.rb
class Curriculo < ApplicationRecord
  

  belongs_to :usuario
  
  has_many :cargos
  has_many :cargo_pretendidos
  has_many :titulos
  
  has_many :idioma_curriculos
  has_many :idiomas, through: :idioma_curriculos
  
  accepts_nested_attributes_for :cargos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :titulos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :idioma_curriculos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :cargo_pretendidos, reject_if: :all_blank, allow_destroy: true
  
  
  
  enum parentesco: {FILHO: 0, PARENTE: 1, OUTROS: 2}
  

 
end

app/controllers/curriculos_controller.rb
class CurriculosController < ApplicationController
  before_filter :authenticate_usuario!
  before_action :set_curriculo, only: [:show, :edit, :update, :destroy]
  

  # GET /curriculos/1
  # GET /curriculos/1.json

  def show
    @foto = get_foto
    @usuario = current_usuario
    @mes =@usuario.nascimento.month 
    @naturalidade = get_naturalidade(@usuario.naturalidade.to_s)
    @estadocivil = @usuario.estadocivil ? @usuario.estadocivil : ""
    
    respond_to do |format|
      format.html
      format.pdf do
         render pdf: "curriculo",
            template: "curriculos/show.pdf.erb",
            encoding: 'utf8',
            lowquality: false
      end
    end
  end


  # GET /curriculos/1/edit
  def edit
    @idiomas = Idioma.where(status: 1)
   
  end

  # # POST /curriculos
  # # POST /curriculos.json
  # def create
  #   @curriculo = Curriculo.new(curriculo_params)
  #   @curriculo.usuario = current_usuario

  #   respond_to do |format|
  #     if @curriculo.save
  #       format.html { redirect_to @curriculo, notice: 'Curriculo was successfully created.' }
  #       format.json { render :show, status: :created, location: @curriculo }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @curriculo.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /curriculos/1
  # PATCH/PUT /curriculos/1.json
  def update
    respond_to do |format|
      if @curriculo.update(curriculo_params)
        format.html { redirect_to @curriculo, notice: 'Curriculo atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @curriculo }
      else
        format.html { render :edit }
        format.json { render json: @curriculo.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    
    def get_naturalidade(sigla)
      CountryStateSelect.collect_states('br').each do |s|
        if s[1].to_s.eql? sigla
          return s[0]
        end
      end
      "Não definida"
    end
    
    
    def get_foto
      if not current_usuario.foto.url(:medium).eql? "/images/thumb/missing.png"
        @foto = current_usuario.foto.url(:medium)
      else
        @foto = 'user' 
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_curriculo
      @curriculo = Curriculo.find(current_usuario.curriculo.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curriculo_params
      params.require(:curriculo).permit(:observacao, :parente_associado, :parentesco,
        cargos_attributes: [:id, :descricao, :entidade, :desenvolvimento, :detalhes, :fim, :inicio, :ultimo_sal, :_destroy],
        cargo_pretendidos_attributes: [:id, :descricao, :observacao, :anos_exp, :meses_exp, :dias_exp, :pretensao_sal, :_destroy],
        titulos_attributes: [:id, :ano, :descricao, :desenvolvimento, :entidade, :grau, 
                            :observacao, :duracao, :modalidade, :_destroy],
        idioma_curriculos_attributes: [:id, :idioma_id, :escreve, :fala, :le, :_destroy])
        
    end
end

app/helpers/curriculos_helper.rb
module CurriculosHelper
    
  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

    
  def mes_portugues(mes)
    {1=> 'Janeiro', 2=> 'Fevereiro', 3=> "Março", 4=> "Abril", 5=> "Maio", 6=> "Junho",
    7=> 'Julho', 8=> "Agosto", 9=> 'Setembro', 10=> "Outubro", 11=> "Novembro", 12=> "Dezembro"}[mes]
  end
  
  def gerar_parentesco(curriculo)
    ret = ""
    if curriculo.parente_associado
       if Curriculo.parentescos[curriculo.parentesco] == 0
         ret = "<strong>É filho de associado da EmpresaX</strong>"
       elsif Curriculo.parentescos[curriculo.parentesco] == 1
         ret ="<strong>É parente de associado da EmpresaX</strong>"
      
       end
    else
      ret ="<strong>Não possui parente associado da EmpresaX</strong>"
    end
    ret.html_safe
  end

  def gerar_descricao_cargo(cargo)
    return if not cargo.valid?
    desc = "<strong>"
    prep1, prep2, prep3 = " na empresa ", " de ", " até "
    inicio = cargo.inicio ? cargo.inicio.strftime("%d-%m-%Y") : nil
    desenv = (cargo.desenvolvimento.eql? "SIM") ? true : false
    detalhes = (! cargo.detalhes.eql? "") ? " Mais detalhes: " << cargo.detalhes : ""
    entidade = (! cargo.entidade.eql? "") ? prep1 << cargo.entidade : " "
    fim = desenv  ?  "hoje" : cargo.fim.strftime("%d-%m-%Y")
    desc << cargo.descricao << entidade
    desc << prep2 << inicio << prep3 << fim << "</strong></br>"
    desc << detalhes
    
    desc.html_safe
  end

  def gerar_descricao_idioma(idioma)
    return if not idioma.valid?
    desc = "<strong>"
    desc << idioma.idioma.descricao << " - </strong>" << " Leitura: #{idioma.le} /" <<
        " Escrita: #{idioma.escreve} /" << " Conversação: #{idioma.fala}"
    desc.html_safe
  end

  def gerar_descricao_titulo(titulo)
    return if not titulo.valid?
    desc = "<strong>"
    desenv = titulo.desenvolvimento ? titulo.desenvolvimento : " "
    grau = titulo.grau ? ((not titulo.grau.eql? "Outros") ? titulo.grau + " em " : "" ) : " "
    entidade = titulo.entidade ?  " na entidade " << titulo.entidade : " "
    ano = titulo.ano ? " com inicio em " << titulo.ano.to_s : " "
    duracao = titulo.duracao ? " e duração de " << titulo.duracao.to_s << "/horas " : " "
    modalidade = titulo.modalidade ? " - Modalidade: " << titulo.modalidade : " "
    observacao = (not titulo.observacao.eql? '') ? "Mais detalhes: #{titulo.observacao}" : " "
    
    if desenv.eql? "CURSANDO"
        desenv = "Cursando "
    elsif desenv.eql? "FINALIZADO"
        desenv = ""
    else
        desenv = "Cursei parcialmente "
    end
    desc << desenv << grau 
    desc << titulo.descricao << entidade << ano
    desc << duracao << modalidade <<  "</strong></br>" << observacao
    desc.html_safe
  end


  def gerar_descricao_cargo_p(cargo_p)
    return "" if (not cargo_p.valid? or not cargo_p or cargo_p.descricao.eql? "")
    anos_exp = cargo_p.anos_exp ? cargo_p.anos_exp : 0
    meses_exp = cargo_p.meses_exp ? cargo_p.meses_exp : 0
    dias_exp =  cargo_p.dias_exp ? cargo_p.dias_exp : 0
    anos_exps = (anos_exp > 1) ? "#{anos_exp} anos" : (anos_exp == 1) ? "#{anos_exp} ano" : ""
    meses_exps = (meses_exp > 1) ? "#{meses_exp} meses" : (meses_exp == 1) ? "#{meses_exp} mês" : ""
    dias_exps = (dias_exp > 1) ? " e #{dias_exp} dias" : (dias_exp == 1) ? "#{dias_exp} dia" : ""
    experiencia = (anos_exp > 0 or meses_exp > 0 or dias_exp > 0) ? 
                    ", tenho experiência de " << anos_exps << " " << meses_exps << dias_exps : ""
    pretensao_sal = cargo_p.pretensao_sal ? 
            ((cargo_p.pretensao_sal > 0) ? 
            ", pretensão salarial #{number_to_currency(cargo_p.pretensao_sal)} " : "") : ""
            
    observacao = cargo_p.observacao ? 
            ((! cargo_p.observacao.eql? "") ? "Mais detalhes: #{cargo_p.observacao}" : "") : ""
    desc = "<strong>"
    desc << cargo_p.descricao << experiencia << pretensao_sal
    desc << "</strong> </br>"
    desc << observacao
    desc.html_safe
  end
    
end

app/views/admin/curriculos/_curriculo.html.erb
<div class=" w3-margin w3-center w3-card-4 w3-row w3-mobile " id="curriculo-vitae" > 

    <div class="curriculo-cabecalho w3-center w3-blue">
        <h2>Curriculum Vitae</h2>
    </div>
    
    <div class="nome w3-margin s12">
        <h4><%= usuario.nome %></h4>
    </div>
    
    <div class=" w3-col s12 w3-right">
        
        <div class="foto w3-col s3 w3-right w3-margin-right  w3-mobile">
            <%= image_tag( foto, class:"w3-image") %> 
        </div>
        
        <div class="dados-pessoais w3-col s8 w3-left  ">
          <h5 class="w3-left w3-margin-left s12">Dados Pessoais</h5>
            <div class="endereco w3-col w3-margin-left">
                <strong class="w3-left w3-margin-left">Endereço: </strong>
                <div class="w3-left w3-margin-left"><%= usuario.endereco %></div>
            </div>
            
            <div class="endereco w3-col w3-margin-left">
                <strong class="w3-left w3-margin-left">Data Nascimento: </strong>
                <div class="w3-left w3-margin-left">
                    <%= usuario.nascimento.strftime("%d de #{mes_portugues mes} de %Y") %>
                </div>
            </div>
            
            <div class="endereco w3-col w3-margin-left">
                <strong class="w3-left w3-margin-left">Naturalidade: </strong>
                <div class="w3-left w3-margin-left">
                    <%= naturalidade %>
                </div>
            </div>
            
            <div class="endereco w3-col w3-margin-left">
                <strong class="w3-left w3-margin-left">Sexo: </strong>
                <div class="w3-left w3-margin-left">
                    <%= usuario.sexo %>
                </div>
            </div>
            
            <div class="endereco w3-col w3-margin-left">
                <strong class="w3-left w3-margin-left">Estado Civil: </strong>
                <div class="w3-left w3-margin-left">
                    <%= estadocivil %>
                </div>
            </div>
            
            <h5 class="w3-left w3-margin-left s12">Contato</h5>
             <div class="endereco w3-col w3-margin-left">
                <strong class="w3-left w3-margin-left">Telefone: </strong>
                <div class="w3-left w3-margin-left">
                    <%= usuario.telefone %>
                </div>
            </div>
            
             <div class="endereco w3-col w3-margin-left">
                <strong class="w3-left w3-margin-left">Email: </strong>
                <div class="w3-left w3-margin-left">
                    <%= usuario.email %>
                </div>
             </div>
        </div>
    </div>
    
     <div class="w3-col s12 w3-right">
        <h5 class="w3-left w3-margin-left">Idiomas</h5>
         <div class="w3-row w3-col w3-margin-left">
            <% curriculo.idioma_curriculos.each do |idioma| %>
                <p align="left" class="w3-margin-left">
                  <%= gerar_descricao_idioma idioma %>
                </p>
            <% end %>
         </div>
    </div>
    
    <div class="w3-col s12 w3-right">
        <h5 class="w3-left w3-margin-left">Titulos</h5>
         <div class="w3-row w3-col w3-margin-left">
             <% curriculo.titulos.each do |titulo| %>
                <p align="left" class="w3-margin-left">
                  <%= gerar_descricao_titulo titulo %>
                </p>
            <% end %>
         </div>
    </div>
    
    <div class="w3-col s12 w3-right">
        <h5 class="w3-left w3-margin-left">Experiência Profissinal</h5>
         <div class="w3-row w3-col w3-margin-left">
            <% curriculo.cargos.each do |cargo| %>
                <p align="left" class="w3-margin-left">
                  <%= gerar_descricao_cargo cargo %>
                </p>
            <% end %>
         </div>
    </div>
    
    <div class="w3-col s12 w3-right">
        <h5 class="w3-left w3-margin-left">Cargos Pretendidos</h5>
         <div class="w3-row w3-col w3-margin-left">
            <% curriculo.cargo_pretendidos.each do |cargo_p| %>
                <p align="left" class="w3-margin-left">
                  <%= gerar_descricao_cargo_p cargo_p %>
                </p>
            <% end %>
         </div>
    </div>
    
     <div class="w3-col s12 w3-right">
        <h5 class="w3-left w3-margin-left">Observações Finais</h5>
         <div class="w3-row w3-col w3-margin-left">
                <p align="left" class="w3-margin-left">
                  <%= curriculo.observacao %>
                </p>
            
         </div>
    </div>
  

</div>

app/views/admin/curriculos/_show.html.erb
<%= stylesheet_link_tag 'w3', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'curriculo', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'bootstrap_and_overrides', media: 'all', 'data-turbolinks-track' => true %>

<%= render 'curriculos/curriculo' %>

<div class=" w3-margin w3-center w3-card w3-row w3-mobile" >
  <div class="form-inline w3-margin">
      
      <div class="form-group">
          <%= link_to "Gerar PDF", admin_curriculo_path(@curriculo, format: :pdf), method: :get, target: :_blank, 
              class:"btn btn-success" %>
     </div>
     
     <div class="form-group">
          <%= link_to "Voltar", :back , class:"btn btn-danger" %>
     </div>
     
</div>  

app/views/admin/curriculos/show.html.erb
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

<%= render 'curriculos/curriculo' %>

<div class=" w3-margin w3-center w3-card w3-row w3-mobile" >
  <div class="form-inline w3-margin">
      
      <div class="form-group">
          <%= link_to "Gerar PDF", admin_curriculo_path(@curriculo, format: :pdf), method: :get, target: :_blank, 
              class:"btn btn-success" %>
     </div>
     
     <div class="form-group">
          <%= link_to "Voltar", admin_curriculos_path, method: :get, class:"btn btn-danger" %>
     </div>
     
</div>  