config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin_useres, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
 
  
  
  
  root to: 'home#index'
  
  resources :curriculos, except: [:index, :destroy, :new, :create]
  resources :vagas, only: [:index, :show]
  resources :candidatos, except: [:show]
  
  devise_for :usuarios, path: "", controllers: { sessions: "usuarios/sessions", registrations: "usuarios/registrations" }, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout'}

  
  

end

app/models/candidato.rb
class Candidato < ApplicationRecord
  belongs_to :vaga
  belongs_to :usuario
  
  enum status: {CANCELADO: 0, AGUARDANDO: 1, ELIMINADO: 2, CONTRATADO: 3}
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
    before_action :set_candidato, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_usuario!

  # GET /candidatos
  # GET /candidatos.json
  def index
    @candidatos = Candidato.where(usuario_id: current_usuario.id).order(:status)
  end

  # GET /candidatos/1
  # GET /candidatos/1.json
  def show
  end
  
  def new
    @candidato = Candidato.new
    @vaga = Vaga.find_by_id(params[:vaga])
    loc_candidato = Candidato.where(vaga_id: @vaga.id).where(usuario_id: current_usuario.id).first
    if loc_candidato
      if loc_candidato.status == "AGUARDANDO" or loc_candidato.status == "ELIMINADO"
        redirect_to candidatos_url, notice: 'Você já está cadastrado nesta vaga'
      elsif loc_candidato.status != "ELIMINADO"
        loc_candidato.update(status: 1)
        redirect_to candidatos_url, notice: 'Você recandidatou a esta vaga, sua objeção desta vaga continua a mesma,
              clique em editar para altera-la'
      end
    end
  end
  

  # POST /candidatos
  # POST /candidatos.json
  def create
    @candidato = Candidato.new(candidato_params)
    @candidato.usuario_id = current_usuario.id
    @candidato.status = 1
     respond_to do |format|
      if Candidato.exists? usuario_id: @candidato.usuario_id, vaga_id: @candidato.vaga_id
        format.html { redirect_to candidatos_url, notice: 'Candidato já existe' }
        format.json { render :show, status: :created, location: @candidato }
      elsif @candidato.save
        format.html { redirect_to candidatos_url, notice: 'Registro na vaga realizado com sucesso' }
        format.json { render :show, status: :created, location: @candidato }
      else
        format.html { render :new }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  
  end

  def edit
    @vaga = @candidato.vaga
  end

  # PATCH/PUT /curriculos/1
  # PATCH/PUT /curriculos/1.json
  def update
    respond_to do |format|
      if @candidato.update(candidato_params)
        format.html { redirect_to candidatos_url, notice: 'Candidato atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  # Modificado, não deleta apenas muda o status do candidato
  # DELETE /candidatos/1
  # DELETE /candidatos/1.json
  def destroy
    
    respond_to do |format|
      if @candidato.status == "ELIMINADO"
        format.html { redirect_to candidatos_url, notice: 'Você já foi desclassificado desta vaga' }
      elsif
        @candidato.status = 0
        if @candidato.save
          format.html { redirect_to candidatos_url, notice: 'Registro cancelado com sucesso' }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidato
      @candidato = Candidato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidato_params
      params.require(:candidato).permit(:observacao, :vaga_id)
    end
end

app/helpers/candidatos_helper.rb
module CandidatosHelper
 
 
  def sel_cor(candidato)
    # CANCELADO: 0, AGUARDANDO: 1, ELIMINADO: 2, CONTRATADO: 3
    status = Candidato.status[candidato.status]
    
    # CANCELADA: 0, ABERTA: 1, OCUPADA: 2
    status_vaga = Vaga.status[candidato.vaga.status]
    
    case status
      when 0
        "orange"
      when 1
        case status_vaga
          when 0, 2
            "red"
          when 1
            "green"
        end
      when 2
        "red"
      when 3
        "blue"
    end
  end
  
end

app/views/candidatos/_form.html.erb
<div>
    <%= simple_form_for(@candidato) do |f| %>
        <%= f.error_notification %>
        <div class="w3-center">
            <%=  %>
        </div>
        <%= f.input :vaga_id, as: :hidden, input_html: { value: @vaga.id }%>
        <div class="w3-row">
            <div class="w3-col s12  w3-margin-right w3-mobile">
                <%= f.input :observacao, label: "Descreva porquê você deseja essa vaga (Opcional)", 
                error: true, input_html:{style: "min-height: 150px;"}%>
            </div>
        </div>
       
        <%= f.button :submit, "Salvar", class: "btn btn-success" %>
    
    <% end %>
</div>

app/views/candidatos/edit.html.erb
  <div class="col-md-6 col-md-offset-3 w3-margin-top w3-card-4 w3-hover-shadow w3-round-xlarge"> 
    <%= description_w3("Editar dados de: " << @vaga.descricao) %>

    
    <%= render 'form', candidato: @candidato %>
    
    <hr>
    <%= link_to 'Cancelar/Voltar', :back , class: "btn btn-danger" %>
 </div>

app/views/candidatos/index.html.erb
<div class="w3-card-8 w3-margin-top w3-round-xlarge">
  <%= description_w3('Vagas que estou concorrendo') %>
  <% @candidatos.empty? %>
  <% unless @candidatos.empty? %>
    <table class='w3-table w3-striped w3-hoverable w3-centered'>
      <thead>
        <tr>
          <th>Descrição da Vaga</th>
          <th>Setor</th>
          <th>Status da Vaga</th>
          <th>Minha Situação</th>
       
        </tr>
      </thead>
    
      <tbody>
        <% @candidatos.each do |candidato| %>
          <% color = sel_cor(candidato) %>
          <tr <%= " class= w3-text-#{color}" %> >
            <td><div align="left"><%= candidato.vaga.descricao %></div></td>
            <td><%= candidato.vaga.setor.descricao %></td>
            <td><%= candidato.vaga.status %></td>
            <td><%= candidato.status %></td>
            <td>
             <%= button_to 'Mais Detalhes', candidato.vaga, class: 'btn btn-info btn-xs', method: :get, 
                                form: {style: 'display:inline-block;'}%>
             <% bt = "true" if not (color.eql? "green") %>
             <%= button_to 'Cancelar', candidato, class: 'btn btn-danger btn-xs', method: :delete, disabled: bt,
                                form: {style: 'display:inline-block;'},  data: { confirm: 'Deseja realmente desistir desta vaga?' } %>
             <%= button_to 'Editar', edit_candidato_path(candidato), class: 'btn btn-warning btn-xs', method: :get, 
                                form: {style: 'display:inline-block;'}, disabled: bt %>                
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
       <div class="alert alert-info" role="alert">
          <strong>Você ainda não candidatou a nenhuma vaga! Clique no link abaixo pra ver as vagas disponiveis</strong>:
      </div>
  <% end %>
  <hr>
 
  <div class="w3-margin">
    <%= link_to 'Mais vagas disponiveis', vagas_path %>
  </div>
</div>

app/views/candidatos/new.html.erb
  <div class="col-md-6 col-md-offset-3 w3-margin-top w3-card-4 w3-hover-shadow w3-round-xlarge"> 
    <%= description_w3("Candidatar: "+@vaga.descricao) %>

    
    <%= render 'form', candidato: @candidato %>
    
    <hr>
    <%= link_to 'Cancelar', :back , class: "btn btn-danger" %>
 </div>