config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admin_useres, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end
 
  
  
  
  root to: 'home#index'
  
  resources :curriculos, except: [:index, :destroy, :new, :create]
  resources :vagas, only: [:index, :show]
  resources :candidatos, except: [:show]
  
  devise_for :usuarios, path: "", controllers: { sessions: "usuarios/sessions", registrations: "usuarios/registrations" }, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout'}

  
  

end

app/views/layouts/_messages.html.erb
  <% flash.each do |type, message| %>
  <div class="w3-container w3-card-8 w3-large w3-margin w3-round-large <%= w3_class_for(type) %> ">
    <span onclick="this.parentElement.style.display='none'" class="w3-closebtn ">&times;</span>
    <h4><%= message %></h4>
  </div>
  <% end %>

app/views/layouts/_navigation.html.erb
<div class="cabecalho w3-left">
  <ul class="lista-menu nav navbar-nav text-uppercase w3-xlarge ">
     <li class="w3-margin-right ">
       <%= image_tag("capul_logo.png", height: '64', width: '145') %>
     </li>
     <li>
       <%= link_to root_path do %>
         <i class="fa fa-home"></i>
        <span>HOME</span>
       <%end%>
     </li>
     <li>
       <%= link_to vagas_path do %>
          <i class= "fa fa-search"></i>
          VER VAGAS
        <%end%>
     </li>
    <% if usuario_signed_in? %>
        <li class="w3-dropdown-hover">
              <%= link_to '' do %>
                <i class="fa fa-id-card-o"></i>
                MEUS DADOS
              <%end%>
              <div class="w3-dropdown-content w3-border w3-card-4 " style="min-width: 200px;">
                 <%= link_to edit_usuario_registration_path(current_usuario) do %>
                 <i class= "submenu fa fa-user"></i>
                 PESSOAIS
              <%end%>
              <%= link_to curriculo_path(current_usuario.curriculo) do %>
                 <i class= "submenu fa fa-id-card"></i>
                 CURRICULO
              <%end%>
               
             </div>
        </li>
  
        <li>
          <%= link_to(candidatos_path) do %>
            <i class="fa fa-hourglass-2"></i>
            CONCORRENDO
          <%end%>
        </li>
        
        <li >
          <%= link_to destroy_usuario_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>
            SAIR
          <%end%>
        </li>
    
    <% else %>
        <li class="w3-dropdown-hover">
          <%= link_to '' do %>
              <i class="fa fa-unlock"></i>
              ACESSO  
          <%end%>
          <div class="w3-dropdown-content w3-border w3-bar-block " style="min-width: 200px;">
              <%= link_to new_usuario_session_path, class: "w3-bar-item" do %>
                  <i class="fa fa-sign-in"></i>
                  ENTRAR
              <%end%>
              <%= link_to new_usuario_registration_path, class: "w3-bar-item" do %>
                   <span class="fa fa-user-o" > REGISTRAR</span>
              <%end%>
              
         </div>
      </li>
    <% end %>
    
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Curriculo" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=PT+Sans"/>
    
    <%= csrf_meta_tags %>
    <%= yield(:head) %> 
     
    
  </head>
  <body>
    
   <header role="banner" class="cabecalho navbar navbar-fixed-top navbar-inverse">
      <div class="container ">
        <div class="cabecalho navbar-header">
          <button data-toggle="collapse-side" data-target=".side-collapse" data-target-2=".side-collapse-container" type="button" class="navbar-toggle pull-left"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        </div>
        <div class="cabecalho navbar-inverse side-collapse in">
          <nav role="cabecalho navigation" class="navbar-collapse">
            <%= render "layouts/navigation" %>
          </nav>
        </div>
      </div>
    </header>
    <div class="conteudo container side-collapse-container w3-margin-top">
      <div class="row">
        <%= render "layouts/messages" %>
        <%= yield %>
      </div>
    </div>
    
    
    <% if controller.controller_name == "home" %>
      <footer class="w3-row w3-margin-top">
        
        <div class="w3-row w3-col s3 w3-margin-right w3-mobile">
          
            <div class="w3-col s12 w3-margin-bottom w3-margin-left ">
               <%= image_tag("capul_logo.png", height: '64', width: '145') %>
            </div>
        
        
            <div class="w3-col s12 w3-margin-left w3-left-align w3-xlarge w3-mobile ">
                <h4>EMPRESA-X - Empresa X Unaí Ltda</h4>
                <h5>Rua dos Bobos, nº 0</h5>
                <h5>Bairro Centro - Unaí - MG</h5>
                <h5>CEP: 38610-000</h5>
                <h5>Site: <%= link_to "empresax.com.br", "http://empresax.com.br/"%></h5>
            </div>
       </div>
       
        <div class="w3-col s7 ">
      	  <div class="row-fluid">
              <div class="span8">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3828.269409878033!2d-46.89194868556414!3d-16.360232841483437!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTbCsDIxJzM2LjkiUyA0NsKwNTMnMjMuMSJX!5e0!3m2!1spt-BR!2sbr!4v1497535479487" width="1200" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
              </div>
          </div>
        </div>
        
        
      </footer>
    <% end %>

    
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>

    

  </body>
    

</html>